{% set name = "pkgutil-resolve-name" %}
{% set version = "1.3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pkgutil_resolve_name-{{ version }}.tar.gz
  sha256: 357d6c9e6a755653cfd78893817c0853af365dd51ec97f3d358a819373bbd174

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - pkgutil_resolve_name
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/graingert/pkgutil-resolve-name
  summary: Backport of Python 3.9's pkgutil.resolve_name; resolves a name to an object.
  license: MIT AND PSF-2.0
  license_file: LICENSE
  doc_url: https://docs.python.org/3.9/library/pkgutil.html#pkgutil.resolve_name

extra:
  recipe-maintainers:
    - thewchan
